adguardLink: ENC[AES256_GCM,data:7bFU3rJNwJq6L09gs5LPH0isr/Ut08QkuC/OzM2Wxm05tL7EeBcEtVrdklDbh6C9oGlEOMQgiIbXII1MPswaZv6Y7wZ4181D1T0tlielOBoWauGApfLGmM1RYntKVypp1tpCbcsu,iv:Zp9LlUonLLCEAE7PMbNg8WasmJ4ELT3iW34aVwYX0lo=,tag:cThB5WmMEIRMr9VDFF9xlQ==,type:str]
grafanaCloud: ENC[AES256_GCM,data:Ju/YIaA1jeIPBXmXEvk4DhmOYq5m/Dd3oL1P99mR6A85UZpTlrTn+zTV1uQum9yGyCdgnlEi7G/cT5gyupErZY1m1s/fgJI/m06ypHGaFFgsmk2Y5Tns+teKQkMIdrteXhsqsFzkbXqF0GDYQaWfEy0w0v5UYOE4v8/NUYNCNYeuRl2nfIuyNtp/hxaLr/zrqPwjAyV5,iv:VLqWHYakDMf0fqy7HBd2DlgIEqSUMdCVFeTwZhF3DtI=,tag:GSK7CpVD+AeSNqEmxgLDww==,type:str]
newt: ENC[AES256_GCM,data:sJ0ZQpgsw0peRLBKIenzHpihkVf/VtWL9089EOYIEkc4hmdlcB29RXlyB/nN+A93nG5g7kd73tFijOgqVMkYilr1QW2J3Dlv4XcEN+ARisixIdw3,iv:jztdRAVVaJMoyWkVNXbPTo2t4wRr1hDWvP0STXpWNgk=,tag:3GlDQ5hvfNmnYmIuV+c1ww==,type:str]
sops:
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUEgwdzdZd0NGYlVKVzVr
            d294bFVPUTVrQ1c3anZ3UnFjdXlYM0MyS1ZBCnBSdDgwNWhFR2ZsMitCclZaNlFR
            VnZGMDlnK2ZKZWJkWDlxbm00Vm5Yd1EKLS0tIEVsNnRsdnpRcUlxemsyQkVQeTlC
            MXowam9PbmZ6WkwvckNqQVZWdE0zZkEKV3vqLqidGeybiQGjWu8ycGjDv4kgm0t1
            5GGHA4Kwda23pX0gXqc05Pwltwl7QXIQm7iuSTYa7l2cbk1qnQDNbw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dks5yn7u9guqk9g8gs7panm6xkr72h9g9v8lnustwg4fsm583msnjma6x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESlpCQXh1bERWdnR2bW5U
            VGh6RkpBWWRON1dDTEFRcVpTWmU0czVCTUJNCkhHOHdNSFpJM2pqOHdvM3FteTlG
            bnQyc1JQeFlmZ0dQL000cWtqQ2Q0UjQKLS0tIC96WEM2OGYrWFRySWhRM0JkNkQ0
            bjB3YlNqc0NsbFNIdGZiYmxQOGpiYzgKk5szeIPubh0uaA3EWos+RtCwhBRVo9FI
            c+baNIG8DHlT0BTcVpAMF2cRwGQVvBNvAtMFhvty/QutaAgG6jz+1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wq3nu4vt2l5m5sfar678px45495h6zkdp27gt95fpxpx5777098qp5t0h3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSDRLRjF3QzdyQ2krY281
            MEpZQTRmZkM0YWhDOXNIL2lxTFJCNVdSZmxVCjl4RkNSdUlUS1V0ZXA1WWVnVndF
            WTc4MTlMK0s3MmpJQitwWU1oa3VQaTQKLS0tIHRqZytobnQyZEgyUkdOQkxmeGYw
            NmJ0c1BqOHZ6djVsNVordU55UGRDOWsKtc1vEOGFKsu8u+sjBo1FdanqQx/OHq9W
            37WSTeJTCaGmUvlD3uQy/ftWZOtjF/JWFraL5YXzYgyQu7Ca5QRvqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-01T22:05:32Z"
    mac: ENC[AES256_GCM,data:3W3UBehOb0WRzl2Bqf0gJwiGqCXTUMeNwxzhcwa7zSIh+25DYY3rg4t9zSq06kS0yz4gkIsh8KkLMM8LGc1t5UXtnZBK43TdG56Q4SQODd5HzWEyEhyXGiiuRU1tN6oeDsq5zTD/aeEE7oXIrTJRG2r627BeO4BpJ8S+k3MQWc4=,iv:AAUr2nQUmfdW29Rbsqxg7MPWjkSZ4pxSqwzonWqHwws=,tag:bO3FSfnxE1REg2pRLN3mxA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
