cloudflareTunnelToken: ENC[AES256_GCM,data:UW52B+YVHAzuzA/8JtbqeoBuw8FXyHzVVj5dVRGQ+IVFxxJfWVUUUDfc/V0ihc1BZXGcdp4AZOgueY2WgV08earCcxi6FRtqbTaAPRQm9hH2Mc+0tZykXsAlpho8BxCt+hD9AYo+dQ2dBi2C8pFy/94yfz7Ukykh+27+0KooTcBkpVOnMXcwPWsL5b95TT1QFxVmGEI71MWHhTtySKXWu8RfUdrgIL30oucPME7QADPCw4SpIvAtBAb+jznS718Vgcj3xINWVkmHkU771mFCqCc=,iv:FYgoFvpWKCWNtq4f1jndE4Sg80eEf9EKfLVgi0t2PCc=,tag:soon69LGlzv5MeLSHeeK2w==,type:str]
cfDNSToken: ENC[AES256_GCM,data:GZySjdxjG1PyRocGg7qEjnWudHPGeV3H5lVVFf8QKWHdsvH9T6OiHjjDZmZWY2tEZCQy424WoEvMptvY+n/mmvvUd28V36aZuuazHq+jScR1ou578+3zgrP2YA==,iv:riYo0Ebo3FGNr35OSFrgKMB8RffODKVlOKtYJcThPSQ=,tag:+fRUslzvWoXQsw+cA+MlGg==,type:str]
sops:
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyc1dxbEVYeHJuelVHYnRp
            ejgwZ2ZlYjNEQ1NQd0dXOWQwMzNveExtUDBnCk1PbGRYS2RkckdNazdoeWd5dlVQ
            WnF0VGlxRkVPTWlrS25TQTB2NkRzWkUKLS0tIEpXd1g1ZGVCNDRMVHc5VmhiZFUy
            Y1pRODBRRzZOV25DYXJ5N1JMOS9tNUkKpz/hMXH1AvkpG65E0lLqi6+cN/dl3BVF
            XICs53rSFnS8er8ohccRJJBr4QKStxfZiLa2u+T0jaXzeKew5murYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dks5yn7u9guqk9g8gs7panm6xkr72h9g9v8lnustwg4fsm583msnjma6x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1R09oajRoWlEvQy9Ic2ZO
            QWZtR2taUklBaUgxQW1saldIbC8ydlhpL3lZCkVrZ2M2dXlHQUFNMDZnWTFuWkR3
            Nm41M1NUWnJIa1BaS042ci9FS2F0T0EKLS0tIDk3ZzZsejY5bVRrclNGbGFIeDly
            UDM3d01BSjBxNHdET2NIVlhPZHpuRGsK7Ak4ylp3Ki0O2DRK54eKeV4zQ505iQgs
            xH5DmTDjvr2aZ0lYM8Jy0JTlW+4LJM1zbAYv+ZBro8/7nYtZMF6tuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-03T12:07:32Z"
    mac: ENC[AES256_GCM,data:DCPHtmCltE6Kk1XPnz9KURDPjZLckC4anmWqm2j0QNVaZpCHhd3st5PWDvnytYKMow3c2K46o3+dQV8KfSLq/JhHppsiCT11J49LqpHnLL03/4x4pqoH7hXgZDVKOYqO3PAAYNr6HER/lcVTrJHI/KHPhhnJTdxVGk5vb7/HmMs=,iv:MaPpwEc+SIm2uUOFG1+hUubUsDduhFAmOFm7H5E2fAY=,tag:sjSHI1phGd2e3xvhWdJnFg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
