cloudflareTunnelToken: ENC[AES256_GCM,data:pTYNZXY8oqLpcwHAbehOEdks+NP4TM35qMZUiNrUKl8TzwpjKFqy1dFXDagsiVSAn0WhZPReathXudUd2xkEtBYcYdbH9Z+RJYT+cOeXNEVU0urQGZHk7fMLm/WVzOZxeVLe/6rXRViq3pJBGrXjrlBIdBlL8LtZH5PbufCgpB1a1rsOAxk9W4tpD5DDVcRbuBQKit4oIQ0eYEdDTG1f+am98zSsnIbJatHAgOTqka/rzELyTTiw970luYz8tqzMQ3RYgoF9pe6rVAXyqpwD1K0=,iv:c0fbdK5wJ//ZMoo8J9r0GKT7bLPFlKWMaxM2Murbv6o=,tag:Y3w9NqQO9rD8epExpv7M9A==,type:str]
cfDNSToken: ENC[AES256_GCM,data:WZIPPAwZuz6rIvKfVDO8SI9MwnWZnGZLbMc9F4d2GyFJfV2JPIEACPXONQ84i3RVEKB4U+Sf2tkSxMXG+uKPijiEJfD0A9RjCvhWxfd+bXo8bQeBZOZT6QwUtA==,iv:wGrdpRtzaaopMcCIAbKAG13KkUkUMJA5OgUnw11EYoI=,tag:wwJEnqU8glfYFeK2I5r1pQ==,type:str]
adguardLink: ENC[AES256_GCM,data:r3Iza/c0IYq/c2J0r1W4YzDgzPIRUvjXuZzjiiR56tzjSK89CpKWWLU5LM1xW7b+QvqeHeFDzqHBWtn6GcDTE4RFhIqL2oYSjzkb/ol5QavQFfFFXBMNOrwF4DgdKiRE7iDSV+i2,iv:+YZWyPwD0zUABCmwc8Ry2OszNS9MSJwVP+8nVydmAvg=,tag:fTO0G8SdqHiKrCjJDxhcJg==,type:str]
tailscale: ENC[AES256_GCM,data:Q3+Alt8p8bbdPlwgwJo5k/3MID6gPTXejk5NVo65pjLlkJQ+G0b2qWU1wqz5IO55fJHj4FW92GQ41icuvHeWjXY+MGxpMPOv+g==,iv:bYa67JVPkYTGzF/SZlp70Tui1Y1schOrEHmx1QmNOhU=,tag:stjLKSYJlKURJ4C3ORvq6A==,type:str]
cloudflareDnsTokenSingle: ENC[AES256_GCM,data:lUNF426e/bBO89WJwaq+J0+/KII88jzEJNuNp6ZA+e2Y8HLe8+Ek2g==,iv:IGUoguVN625ONSBe8xBV1d2eZhKTaRdHTAyYiInweaE=,tag:356CIrOaSbXgUuwtP9KwuA==,type:str]
sops:
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVEgrUUhnN2RBVlAyNWFD
            VmRGbEtDTkVpcEk2WEFCRFRYK0ZiRTcvblVrClVhV3V1cmhZWjEzRUZPSHJoT2Ex
            dU1SOW52RlgyTUVCLy9TNXVhQ0N6L3cKLS0tIDBrVEFqaFBWY0REMUNvM0VveHlh
            QlBjK0FoSEZvd3FoTksrRDFKUG5xeEEKoKji3T1O5iC8bD27D5XubZwgWoRy8ZRp
            RYvwVIyz/3EXCZm2I8YKbEx2hGSJ6LLUjtrQnTqqlSK+IvdpirEXNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dks5yn7u9guqk9g8gs7panm6xkr72h9g9v8lnustwg4fsm583msnjma6x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQTV0NFNrdjA4aVJpUXlG
            NVFtN1NWQjhHZW90Qzd3K3k0M0k2ZldJb0NFCkVXVFVxSVVTU29mVjVtR0NjMyt5
            eEU3T0VlOUJJMnJvYjAwbVZ6ZmpvSWsKLS0tIFVqS0hYZnB4K3l2Qm9JbXd6VDdF
            Nit5ZmhldVd4RGhpSHkvb3QzRmliNU0Kt9jr3f/gMlhtQY9xeWjcwza2cseleZrF
            RlsTlMJDGhpkigPBfbgdEBVVA+qtmp8bwPZueMFdIOaZm3Teo7E+CQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wq3nu4vt2l5m5sfar678px45495h6zkdp27gt95fpxpx5777098qp5t0h3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VzBpbnViMTM2eWQwOFpx
            TkRPckNmYWNaTFl2Z2pQNDNabTA5dG5NTm04Cis0bTdsMy9zaFZWTGZSeUJlaGR1
            ZFRxM2s5NzMxSmQzRS9raDQ3RzVVU2MKLS0tIHJVTlJmeWlJM2UwOVY4aXVCSFk1
            YSs5RUtURlRSTkpFeVVyaEg5emc1bDAKMIY44/7q/JHTN+G75T0XFhSIdIFpPPwW
            Y84Izjz/8Ap41jnDZi5pLRYSmCzmVUJ56vX3TZ2+hgv3WA3Nt/DTGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-21T18:22:14Z"
    mac: ENC[AES256_GCM,data:DtS1UZW4kKYFvI9H/Zc/mReXgq/Cq7xYpvD0MdQWVLEFxm14c8T1IKFK+yueTsD/0jcPjXsh6QyoB92AXdETnQlgSHU3q0xoOpkTQCE5uKFvK1yQ8cSCByfTKgHOrPlddlxElvvrrjz2OU391wjkzk68jCFZTNCxMpcFtbpCoyk=,iv:XCVVIZrIHhTQbYSEEH4H6yfi19r9bhFDSb3/wQGuglE=,tag:gD9va5OB4OwYZwVr/yngvQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
