adguardLink: ENC[AES256_GCM,data:JelGQnyNDRN52i8RW5bcXHsXDSYE8QoEapBvyDutAMruMlMmdjjm6rEG7G0DsxEIICxB99ja/UXqfLv+vfGIBp43WqbA6w7ECPXGShqm+w8/la/OzYWk4Z6UXRR3I4snfs0RXOov,iv:x5S/sbibKKBETdCl0Kp8Da3ZoT2HXSkeSmli+Olvs8Q=,tag:Sb9YVkSSlb7Sr7n6wzOiCw==,type:str]
grafanaCloud: ENC[AES256_GCM,data:Vb7keYNbo5GMglGvgGnDRgPJB2Fwv7Ljx6NRoc5L+BjL9162y5LweLHyQxwJeRHxFRFqnUhdxxmcAJcqF9xeI35B2PQ/qMxEJFajkY1KZ3csGnFpbZc38831dFF3H0MjpY51vfH9LwQtgua/laEb8HYmN4PGzaVb+AIIfVuAgjJvkx7OA4NBRXYuLnKqvgu288mPGYQr,iv:bUs92AsEZ1y3gh4bM4V/n3bnDnllY/i5ngMNiAy1+t0=,tag:JjLfm38fcFaSwrZaDEdc9g==,type:str]
sops:
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RjZFR2pwYXBWaDl1cEhR
            c3FtS1VTTUxBTjg1Y1RiNVBzaEY1dFQwcTFvCkRna1E5UHFRQXVGN2JVZi95OWpl
            RnA2ZlNiZW5KV3dSOWQxbHJBdFlZT1EKLS0tIDlNTEtWWDluOTlQSUFHU1FMd1Ba
            NjMwVFVEUW5xS012dFVMQ3BWdCtVM0UKxahrgt/C6xMkZ0fR+1G589BPeUdiIQm1
            1ySyottbUvDkcoZbFj3fC0GncqXtAXgLkxe9fOFKCBOoLEBTALuXhg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dks5yn7u9guqk9g8gs7panm6xkr72h9g9v8lnustwg4fsm583msnjma6x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQ0M1ckdPQVRRd2lTTTlX
            MytmbjV3VVVJbm5zeTVMelFUYnJES0ZUbTA4CmdHcEs3WWMwRXdTQ3dJNVIzRHBU
            bllGMVQ1SVFtdXIzTWM4V1JZVDNxNHMKLS0tIGxTMzI3aTVRcGlBSzZucTVIcklT
            QSs4SElnd2hiNGd4YkFOSnB6RzBtMGMKlZMUHccK57igPyb0tm15KErQJP17V2CQ
            nRW8GvcLkEC6Vr2mSrw0Un7lkx5VixDqaQgKfspr9MLid14IEW4jvw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wq3nu4vt2l5m5sfar678px45495h6zkdp27gt95fpxpx5777098qp5t0h3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4V0lMc3lObEhxT0ZkeEg5
            b0p2UU1WOGxES0VWZEFMMzRjMkVXVTJMTXhvCnpsS2M1K3FQZkpCb3VWYTgyN2ZP
            VU8xZmhYd2RiL05ITHJBMllndE9oYjQKLS0tIEZIc2xoaEdXTTQ5TUhpc3Y2QThS
            UjJuTW1aT1lRK2s2aGJUNXhMVDdEQ2cKkz1Q2XwDx5yfEwtmKmbnbvbbLgDdqsuH
            FXkgeFuqYZM/7j2AJ+CQKWY2Y/RNTmmiU7JaCdDI2PFgKvX+laZmUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T15:46:36Z"
    mac: ENC[AES256_GCM,data:mdNLlenInD2cVckcnUWgyU8ANLQSewLT/WTqWvvr//JFM9QDR3UUfdizVKCPZWZiCp/89tYAxoY0APOxLbovrUjtMMHkqDIWmRIpqd7O9LmtxME4o8DviAmT42Tt3qxc2LpPB1Ew4vzUSyK4i0zsezg8ZWaqOR2yA8/PwmDjjAM=,iv:a2hiau8l2YrWgoFkOBnVuNKz8Ah7gw5SNem3pymXcL4=,tag:Oo2S+GEwHv6htcImJgVEqw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
