cloudflareTunnelToken: ENC[AES256_GCM,data:HK4D2P+5jr5YboV+2oEmYMmrgDocmHKHyK7BppISWFMeOHVnA63Z/jBHPYeQXZvOOaxxv/NCNShhtpG0b2yBO0tVChCRMm7B6e47KQ931GSB2UR38oqxrZVd9gReFBT9ycnsnGzuj4C6Hk5N/HuD1zH3+ibcnzsUSJpg8v8294M2cxK9X9katAPaWYsKkBcaK2eM1nnK+JWRZN87BrlSOrDQBOhwWPbnZx8h/A19Z3Y1vmF9y+GB1kFpJkHlnrTzQLXTRmld8qi2R4dtoxN/6TQ=,iv:LMXqwFRDdWEJw7S+niWbYJZCuvhQKZBMQYe4gQ530q4=,tag:l31+9CE5neiiadxGHpnqfA==,type:str]
cfDNSToken: ENC[AES256_GCM,data:fZe3xrYrut49Ti83/P/PjcxPnm5pIXqzbmMN+LTOhmVUH7V8AlSF5d7jgISlLA3GmNGQELKl2kRBqEJQ1PLJGoCgMyFuIcuD9EKsTscLKqDP0gT78W8nwTugNw==,iv:S35Hbyv0dTT0yfuzjKvfzzU+ympHcKLvTYNuGcnrARw=,tag:f+oiy8UjsND5NUpcynyZ7A==,type:str]
adguardLink: ENC[AES256_GCM,data:e92AZmiBZi1xgIPcDFnC9PVrpStb5PRd5aikSwuq0PmQRV/D7tsKhqPYvyyo3GjKeOha0NSsxYm0J3dvA/5DSrhKkKbTEtQ/FGGu6Omd8fl+8UMmyRyWcrhO1dNou+ruQQWlN4Ri,iv:afxYaWNRJ80Bw7JJEFDGT5N3RL1lBVFy9JsEDskYCT0=,tag:SZrti/YfhZYa58t1LFeSGg==,type:str]
tailscale: ENC[AES256_GCM,data:PktRH+xWE2jNcEZZqbtLjDv9Zlv/kZUipjWPkF/dbNyf39orZPjyoPXbpMwnT988KlmG2bnU5HycVq8A5WbeKI4EBPkZmCjO9g==,iv:n+DiBIgeN16n2Edv4zba46M4NX4uJDDpTeYpa7Dph4Q=,tag:xzvT1RpD3GRne+QbIfP0SQ==,type:str]
cloudflareDnsTokenSingle: ENC[AES256_GCM,data:WfdYmZs2QfOfBMfZR38Ie/dsYSsgiB58jkvZg9W9MRut/S+vB2jR8A==,iv:TyyywS7R+ziweeR2XdByDyDCqAk2xpEBIC5LqhfAEeY=,tag:nT4LkFXaQZdZrW+P6WZyCg==,type:str]
sops:
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYmtZOW1YMVo3ekJ5ZTBZ
            QzhGQVBFd2pWM1FXZjFaM1J3S2RCNm1FenhZCmJGUGJXZUwrUTliRlJuSFR4MGVu
            YzlsMEtIZE53Wm5sRm0zNXhaRXRJYU0KLS0tIE1WZEVqL1o5K1BUWTIwN1lRQVBm
            bkErajZML2EyR1lRcjhhckYxNFcvclUKycpNqvm+I9LnbnWwE9Mcwsk/4kKVC4Y2
            /m42Co+txJN0Aj9cnwvAuWIUJSALcTKTMvCZVZNd61Tsuo6sLIkYPQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dks5yn7u9guqk9g8gs7panm6xkr72h9g9v8lnustwg4fsm583msnjma6x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Mmh1TWg2RzQxT1l5b3lJ
            S3NkRU1PT2dZTnNrMDIwbHhMcFBBcG1leWo0CllxaU9JNFVLQ2pUZWM5V2d1cGw0
            bE1BblpNOWtrdFRqYkZGdjNkZ0NpQk0KLS0tIGVNWVZ3NnBuazBQcGRrMEtRUDJs
            eWZrbUt3N2FPdkpiODdMMVBPd01nOGcKEFtzYVHILxuBStt0//6/e9vozE1peKCY
            sYMSG/B04IFyDEiuetfXre5bXXXNCbFZGMmbSXnQMpviPUTgHx+ScQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-05T14:00:22Z"
    mac: ENC[AES256_GCM,data:lxkYVZIfZ2qoSwvaDH3HRqTltE/np2g49rTNEomFo3PkyXyBKmFAiJ440C7hH4KB/q79RmVYaAKeNWBZKOYOj8ccItal8MuHL3U30O+muEjE2Lw1Xu9bbzfCH/0yO8Odoxczo2D0lyOMRdreFBuyr5EohieXGdXkJQBxSRNv1EI=,iv:xXtqE0Fci8MTXdSO67JEXVEb6Mfq4VqgkD+gmmvBhF4=,tag:newi4TIE4pztIo4XGAZmZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
