adguardLink: ENC[AES256_GCM,data:0uieN2mnymvF1t8vWsFU5y2SWHiVoFCxoUm66pY2b0PUljIx3C3egEKz4uM/f9TlZa1pMAK4g9bBtcO3/BOak9oTSP5XCFTAbr0j9XKKkU+FkhDh9IjmpChAYM6+eC0sEHZOT/VY,iv:9B1j9JFEWmzWLcZFJiK88FO3xmbD/lV1L3C+9u3juus=,tag:0cMju6MOV75MX+lSKlws6Q==,type:str]
grafanaCloud: ENC[AES256_GCM,data:NoFWn2swT+0NB+695UcwzJe9UXVhVzc+BXVb+qcBOnsCZz4jjlbmQUn6DZsIWWkFIIe5npwLFZNcx5nhjMXBdnBcn7QwbOK3Imm3C0fdBAgg/RPN0tRGmmvU6X3ib981VoK5uM143Zj900E2DKPqj7OF8MctWSqM6TPOiYn1vJUQqa10cDYZkLF2JxPQ8SgK01ZT3ROa,iv:sS1/AGk9Url/DM1LAPBwR7KR616kohxqUoLPMAaZ7N0=,tag:yTPf2fHRMSmA2o76O0swlw==,type:str]
wireguardClientKey: ENC[AES256_GCM,data:g982XGQ7evV9/VEBm1gq1GIdeN+XJtwM6iMgtrxeI48kpmWiPLMpG6Re8fE=,iv:DTlFOxtq6PIFKHOG84ph9dH4g2IQz2sjDyLBRrLZdnQ=,tag:WdV/fm831Xm+brfM7ycwdg==,type:str]
sops:
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM2VxekJGOTlIYVRCMmtT
            SllVU0FhRGM4dmlJWmtOWjJKdWtxSEpBU1E4CmVMOERlYSt0VWhvSktjWjI2RTlt
            TnFPV2RDSVcwTUIvd2ZnWW91VXFjOHcKLS0tIGJBc0h2WkRXaDJubzRhZWxNeFR6
            SEFlNXRLbEdjWjZycjdidmZnamN1SUkKI98rqwYHinNuN1h4VcCFTxbKdnINSH3v
            IFt+HdonzXe85wiSxR/Jm+E0jqGZckJto+7ox+qChjmGBQ3BR7DNcw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dks5yn7u9guqk9g8gs7panm6xkr72h9g9v8lnustwg4fsm583msnjma6x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMWdFaW9GQzNxbUplNndl
            UGErZGNCMStlc2RUV1paWmlOV1MwbnZxdXdjCkVBOG1nbmgvQkxhV1llcUttdWtW
            cjhFN0VhQlNSb3JUQ0s2Tjh3dGh6YkkKLS0tIDRaVHJEWUdPV2hRM25UR0VTc2dR
            VGwvVXZWa3FlMmtjTE1hR1czNUw1aUUKSVI6ZSw6Z3+x3RgHIDqtK0Hcf6SoOHmT
            5zvrv8TWalwKzNj2vwNuc5W5yZBa9BBMKXw5dICP4y/hiXsnHpL/5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wq3nu4vt2l5m5sfar678px45495h6zkdp27gt95fpxpx5777098qp5t0h3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RnkwblFsYmtBSU5HQ0cy
            RFVGY2Jxc3dqcHl1aGc2Q0kya2FUTmhhdmdzCm95VHA2R3ZWUDl5b2tNR1VhNVQ3
            WFY3d1dmQkN5QldVamY3cVp3Yjh1c2sKLS0tIHhsNDZwQnVyb3J1cmtxMUFBOThK
            djlmTmxSS05xVy9xNjErbmV0WWRZK2MK6Ddsc3yZ/gRPGEaCHCo8/RfMpg/nEtp2
            KQNoDaq+1Qfsy3JYYBI4UJk4DkL4KFEqtyAQ6ozU+PgBCfLGJ9d9Jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-14T09:33:13Z"
    mac: ENC[AES256_GCM,data:lBUkBfa+7DpyYPOdQAQJvlAzLSEGzM6NHxQERrrHRpNv6oSvKdHdh6yFedWWiWpDSfLm3P5/wEioKoRkJP+2RnUOmWZNLArHCJewv+05e7pREHn/FOiNcWgTDGI2A978qq9KaghopPLhnemKHiGOFXBwdKJ5u+eO7QCuy0U0hSI=,iv:xUjPeu5ZKCNVBbzM6OFPB4cHE1hT+SwIazP/kwLSs+w=,tag:h1KiY2JWaNXXmfp3ywjIqQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
