cloudflareTunnelToken: ENC[AES256_GCM,data:ff7l3coL9hL3/tpvvqHRwdioYyJ4+H4eLZxxeNH/DPmKQui+TvYskxmDt6AWkr/uxFahm+U9jrZ71BwxP6mdWpB0OX0PZWhhcV38WYBYRMvrtXVYKMg8Jgaf/dAQnnmZ4oA6e2yG4kqYsR4WwghBtFKrbRTB+webDh1nYSfYmD61FZ1JkCf4clm7P1hf7jFDT5iAbyGgyrazlLDkXH/SsQUi15lmm0KIaDodiHJV6pEip18AasOEUTrUKm2uD9ILBD5exYk25KjutlHo3qhwA4E=,iv:+XEk6xpqs3GRZFNcuwrGRjIr9tuXqSZ0G2YIsnbCG8g=,tag:PSOJAhnb3QsSjgHIpvVjVA==,type:str]
cfDNSToken: ENC[AES256_GCM,data:5ZKf9bnhdebNMJFvbN4wKPM8x7init45Kdry9nnXY698D9x4zbimfUOYwzgaQhwp0Au5KfaXAMgzUKXMiPnD1YZRZYMw0XAvVq5+SH2zZFmD1QEHSLgPdqu0eA==,iv:4K3kC8rbujSzeWzKa5pbp1IxoPF6Wc6AyXuoqkopmtU=,tag:yhiqhlivNt7NOP1vCJte1g==,type:str]
adguardLink: ENC[AES256_GCM,data:aAOGMpn0Lv3nQ8+hJ7yYjboAFGp8D3i6VejKWSf66meykMkkX3DpyVKTAeqyK0cc1QsiD4cARD+ty+BQTkUd26QJaRSu3A3MKCm6mwR1DlUB0AyXLZXTvDeUl0qRZV3VGAuvh4dD,iv:hPET2KzI0+U/JatKpbDQW0qStkRIjH5BQTeggpon56I=,tag:1V3aIwSPCKddlpAF7YQlfg==,type:str]
sops:
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzREJFbE9TaW9IN1dzNVho
            R1RvYXF5M2MzdzVXRDNGemRPM3pqd0VOMUVnCll0WEZFQXlJSlRYU1JzM3RsNEpE
            Q2dJK1hUWG54bUlWSjljekhlQzhBMzQKLS0tIHJVRU03TFllK0VTMHl3dlYwU3Vm
            bHVyQW1HOTFCQ2lDSWN3dzJsK3p1cDAKXPlcTwBh4WtAmbdd+wHFeqoiETsb8/o6
            fuDeNFiKdXnXmaUKemL/9ZGWTKR9ZzvO6GoSVuVenQl5aILBhejqWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dks5yn7u9guqk9g8gs7panm6xkr72h9g9v8lnustwg4fsm583msnjma6x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMkoxcTliUjM2dUw2dHJB
            NkpXY3NYRVVLcmdxdHVRMVo2UHAwN2ZYRWo0Ckk1cGg2NXIwM2IrRStWekRHYTdv
            UzBWdHhwYytRV21BVkkvRCtYakNjaFUKLS0tIE1qbFkvZkVMK1NzYW1yMnU3SDVU
            bm9XNTJvb2Uwa1puLzZPRlZrMGg4UE0KBLjwqqE/B6DDOtkZIsCtg799pekT7gJz
            q1H2ht34wvOo0cJ1rj1htFlSq04y8F/0D2Vduy3DdpYuXm3yY0JHZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-04T13:23:18Z"
    mac: ENC[AES256_GCM,data:/zskx5sTFW01jlrVUg+T8sM4TwBhEcQZANSPqoY+Qt5K4fRUMkteb1ymadIfi0a+cCUyeItRcEOUXIsXYKZ2ZA/4gIZoa/1PvvkEs9NoWN7G1g7h0G5chi0fK0uZbQkpbw4z63VnKBLe7v7Ct8mw7D/N5olOtxGhgTnOzhpyz7o=,iv:cbO2pwDHfpTsV0YLBFPUgUcZOCNEfyvtBfDDI5/yP0s=,tag:A/9oOgyM5JKzfq/4LrdMBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
