go-github-to-jira: ENC[AES256_GCM,data:3Zoz4cQuwNHeg++37qm2mWDrFq5CL8a3Gr4po9IFWLl2rsfpaU7gUOjx6U8us1/1GF5Had7VMUcdzVASyvHhxlOJDHzxqU5yiNHft3S2Cy2o+zSe70hckyTStfSYu6samBL218t07kUU/Hivct6iDjVHfly+olR1+vV+zzJqRIEFxkdLYe0fCmDYcT6AQCXUP5dlDkTY1cNv1hM3STWX5UbiKDbeGZeBfm+hdjixk54rUUqpqVzHZ6DPCPbdKelrZIQLn00B5R0sxfAst99Rjot9Fp5YEdXbYtZM9LB9uFOcOu4M4OwmX0p67/tA+7eHdVWW5ziCPRl8FXCEbynDaLWUSJSyCcbfmVS/wehqwArnq3KDnRwn9v+Kmlw5jCAOhit023wW0Atg5mIXopRNiH/MQXcFCHylN1wTx6K7RYWZPCHkTZnKM+0ubOsFGoV8Qw8iHEOwB6ljoI+7VeseaZ0484h6Kb/a/jp9NWxDOBmCmOgYleY4QaA=,iv:4XQ3Vj7503UNlkYvCGUupI3T/J/NWCLK1jAIZ4JwNDg=,tag:TtSNUStE1zt1Dd/iLxtvmw==,type:str]
nix_secrets: ENC[AES256_GCM,data:NQ3bWlA3Dj0eeNsRZaQnuh61tofu4oFt3N3m16HqKhtQKgfl1roNbhx2aIddCG4VB66l09aTS3i3rCkwBA==,iv:PX4WcZA1xfh9nucA0Iag/gyWfJHGbXbQyw7659M09GE=,tag:1VQxf5a1huiRR4PP8RZpEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Rllla3NqSGJlNENjalFZ
            VmhUaG1UeDlDRUVEZXpoUlo3YkVOdVJ0SkhFCkJhcFNLS3RWN0xFZkxOdGNiUTU2
            Rm9GRld4YUlnQVl2M2RtMjhqMm00U28KLS0tIHVoSy9sZ3AxNll3U2QvUVJHV0lU
            c2VTNTNHczF2bU5WbDZvUlhtajFadDgKeGeRiFnAkw3CKQX+mZ+qRUR84d5sXbE/
            lc0iXf1pLYsnfLtCUycuTUCxHVTNQTYKT6kIvfFo5zydr002OuAh7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s3upav4x8re3wzwvuykmjakk52d8xukw7c9jxa80z8zj0lyxgyysenzhen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPV0w5clIzR0hibnRWeExx
            ZzFaS3V0TXFrbXBIWU91aHlrYUhESHpBc3hjCjBpZmVEb2pUNWZ1aTF0MmJGemc1
            a1ZnRHc0cE5MQzVmNkRIZEdIMms0WFUKLS0tIE1xcG1RRTRRNVdZRUdqL3IvT1B0
            ZEdhcDhJaEdYQkYyQjZraytVYVVwS2MKyKqOW6LT82bBB4aGP1vHFIwT7TWdkphm
            Tk8+gULSf+qLyhY51eJGEXgZIkDtHDGngaxjcX7w0aIpyvEkx1zzSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-13T21:30:09Z"
    mac: ENC[AES256_GCM,data:ioFy3nqrpqpyUQUeO4UAdJx2/teip1zSc8rjJy4lojuSXesx9BPxTM0KQ8812pSC1vFxcXhvdhj9RsqMS6D6HvCOGy5XPzrDmC66FgvUMxWpMBYqTU7uEBiFhbnpOz9ZLgssvqMhh4Ww6NBj8FelZ5JrNZuO2MhREl5lGp9MS5E=,iv:IBdASB5RxO1qZXP5EDyQ1Gf9TuTF+42pr5dvxDc5nLQ=,tag:QM7fmsAaiBJpHJYOK1szww==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
