go-github-to-jira: ENC[AES256_GCM,data:9JaNBF5JK2Hpy/0+wdedbi88xIb8h39Az8rGfp7oCkrdqhY1TphqNMvbBK/hKyVQMFRe75Mz8HMRo8nmB2uFhEObX+SzDtT5DFHKzvGVBSnIrfr79jUFuEo5gu0d4M+N2h+PAeWZuk/e71JLkgo2rvrMPNRA4fpFCBdDBD1s/evbP7wOUkhMlXoOnRKzT29T9Mq4pY20G+Hat4X4A4PAGAMc7UxoFRw8F72GYPvUO8b9vgspq3CCGB6y/at/9Xy9srMOmKFZofNLKl3e5U6LklHRh+ymI182Qn53voPtZY8zNDIWzo2cMs8EXTozpZ6uHNwynavHAzoenqSvSpzBOn0YUqTbZAhirfxZ6/BSb+qDJ8hGiVRLJWPP9noX2PFjOqmo4ZzGRAFbb5plOOjXEc55Iuo/+eHMrkn0wvC9ylz+GoisKxVnGAeehm6ZehkgcLbVtRcd5zCbcw/0/qpSWouZZzuCDhmRZVRzKzsjxOAVRBraY+K5xuo=,iv:JZVSKuTBJCbwMDfmyIvFHOuF2EmDObwyzPc6RFqyi+w=,tag:CxD4yW5JmQqq2cazIlRC3w==,type:str]
nix_secrets: ENC[AES256_GCM,data:zEpnnNr4WnVdJ4W151icb9muYY8k9BlL8QlpE3kjizm3kE5p/JvJkShf2MwOoD+9ivE1xe/dU+OdNsJulQ==,iv:xpiv2DC0+udnJ4oWf6OXcPq7OWjRuAgoMx2LNLw7I7U=,tag:XYutH9aDlYoUwhkUUl1HpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERSs4QUxUTWdsYlNqT3dw
            TjkyRWtKelBObEIvbi9ZMG5WendRNnhpNzMwCjJFZzFsSVNrVFY4c2phZm9qTWMw
            S3lqT09YWnZtKzdvTUR4V2t2c2FuazgKLS0tIFE5UXcrZkZySlRSeUlXSm1xQkt3
            OVlxd1dPZnNNV3YyTEY1cWtraDQzUHMKTVRSm90TPxB0MjcKsb17UWsIbT31Cxbl
            G4CSZ/JuS3I4/ogJCK738U9x48T39kiWIHxWlXbK/KO0TEcSoazLAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s3upav4x8re3wzwvuykmjakk52d8xukw7c9jxa80z8zj0lyxgyysenzhen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYS0dhVm45WXhIOTNvT3Nu
            ZnRoWGhjZWZCWUlRaHFMaHlWME5xNjloRGlZCk5vbWJkQ3JCYlZQTHErQUxqbTh0
            bjg2elRYdFZnTTJKdlFPK1Vua2ZTbTQKLS0tICtLYzV0Yk9BZkQzQzdET09QTVl1
            YzMrYnEzaUFyRHYyMzlrSSt5MTBhenMKoszYJZE7ICegOJp0GEkfDQ38diTyLSD2
            gfWGyR3KXffpHNYo0YcJawUgBP69vMwvCxhffolSBZnRzdtbSLsXCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-19T12:59:42Z"
    mac: ENC[AES256_GCM,data:W4hxaDdd8xxzDS2VGRHrz4NGSZpgRd9GCOx5jXOO3o00XXtwoChRq0RZecqULP6DkhBUP9YlaIrWsMJdv6Vj6ptJMUlK7jJwgI2j+gOO80C06SOCeEPAyM1XW8qYJysQ0LHSPdd+cpbJJJUxFqWtD2e+HebOk+clN8KJUDdligs=,iv:WfBCEk4k3cq4sifLu7T7tydlEylz8UIfT3UcODypuCM=,tag:sNVASo5mAxvCxSsXonnsZA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
