go-github-to-jira: ENC[AES256_GCM,data:7fA60SsSwjlczPDFJhcWUZuBnpMa3/2EIYQ4gtMhpBNOcK+E4GP+rRM7xI5GyJV07pElMBhTH0K1QBl/tSwTHqhNjNBykDUx8t5XWmbKuprtiySNoYAE8hhEIexaGDlZOaqT8Wml+YqZew10vq+3HNFU5hMGd5xB/TWENQM1IhKt4JD+flz4Gl/WWUhs4TdtRnn+ozaBf9+kxc4is4t4S7dT6crnMfUQ0K2RSfWq52wblozqRm1Cbi1482NPgKGdV5YG1Co4LvgXtZcNTuHP3pXIpYMMLBpm6KpMxx8y/8FJmhsnaEAewLt1SyGF3g6lUAHypKMOvbkjY58gPF6A9vG8BR7D6Wgm3R04Llb+4OFbWKypGo46hgaeMx+Q+bqTG7C9k9AOZGzcVEY+WE0OM56UkxoqfRTlNa1C2M9Pb2ba0wDzWMIthG0L+XaRbqcI2QJCv3027PiiwPg/hqxGBE4bKXnazCPh1ZUXIwGIMM98cPsrPTbXmGc=,iv:O0apj9niYUWcg6bI436fPmqA30qD0ttz8aJmmA84Nyc=,tag:lL95mySF0Bwse/NawoPqWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVjk0aGJsaG9PUGZDNjFN
            VTRVaHhNWGJ1STRGYkRBeDJrdFhFTm50VUVNCnEySkpnTGNMdmE4MDc3QmRLTHcx
            RHVyckVHNUV5c3h5UVJYZnJtTzNLOUEKLS0tIExxeWU2cmJIdEZsRk1aOGJyUk5M
            Mm9Md2pKanVUYkRzWWtwbk1PR2JkY1EK3O5a9tSP62M190AEyoUFpvBAyn00aXXQ
            F19UnjiJzCPIsmKF9Nta+lD64OTIytVWcRq0nYuFaiiwktp4DhauEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s3upav4x8re3wzwvuykmjakk52d8xukw7c9jxa80z8zj0lyxgyysenzhen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRS3lTOWNwNkJ1d2x5dnRo
            azlDRkZHcDhXbW5TZURxLzV4akZ6UDZPUmg0CkFCM2ttclhFL04wL3pMZlE2eEsr
            c2xEbk4rSmExaThiS25aRzJXUHVveDgKLS0tIDZ6bzFXY21vcmlTK3RmVjlIcmlh
            QlVnRGlxWXpocUloaFQwN2w5akFXdE0Kj5Wl0+PmxnAh4SxknOwGhDT0pffiqjSP
            XP4I5ZFolPva71I80lCYUMpLMcZcZhtIYEvOoK0+fb2DRUNuJPuZMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-13T20:23:55Z"
    mac: ENC[AES256_GCM,data:f4j1baaH3Jn5vYw3g+Lwasa9IG/bonunh/combe2GzCXXboo0Py2z5pnKjDWQldH4Gh58ug4jvdumev/fumHN8IGUb+MweTTpQKlPoFKWfHe3cRPHqKwM7Lq6OIobQrWUHqqZ/06o1C8UHOByzQAEmxDD36K811cyHniuzXwWpM=,iv:2u1wowQmPOTPzzhW4QTMqb432s3nWTbKtJFMji9wVnw=,tag:f9jKanp0Q9Hc2uHLfCRp+Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
