go-github-to-jira: ENC[AES256_GCM,data:3L5jW9LvI+dRKkPd2w7HjiiOnlwHWzD86T7XRAFbtXpAFjIyAlBDMqGMIf5Kq71Nc/tzVqcOA3pHCcr8J7fSJNuQoQwEyhiOXGmJ9G8c20ew6nDFuamMKWWdeaxCcrClRzUen0dZo8zUQepOUAsdRQU9nUh62KHS1polIzIp/iTkovMIMv0LO2q2sqbPO9ci6Ej4zEAQz7b3Af4tK2pimI7di8jqlIrdEC4r8CVWGbi5Mr3dgG6rch4DgXKwaAmHkFgng/tlhxC2trYauvVPk2XiP1BxHfH4JmwwU1JWY2OYRnjc4NOiqjO4YfE7K+Zvqtqz86FBIjODDA3ur2O07Ud5uAddYJN1QsCiRtHX3HgihjT8XNKYrQ7qgUBY9rF1k1rbYiWmhCjFZSYAFleUsqQkQpD0a2iATt7cOfQ2kD/6tG4co/QlyoB1omPp40CDK/xbADr3WHJQaAG5oD4kQ5VJhiO7aqIRp2+sNvJZAVAzW//tRb4m7/Y=,iv:tiz+2/iCEvfpLpnmMor8+QRoFAT5KuNMHEgo2kz+ZZA=,tag:S1nqd+wuUm33kQKbQQNozQ==,type:str]
nix_secrets: ENC[AES256_GCM,data:jnlhhMQ9y61FTmNizJKonI8ekD3hz6OGu1QljwZCx97kOT3gEDwRtn6Ekd3pBQCgEVAfF5kVpJctlAFo1Q==,iv:D/rEI3yAdtoHn6gQjjmA5c2XrNsseIcNuU4QYsiG1+0=,tag:LKJhBgfOV1jvw2LjvlVz/w==,type:str]
nix_ssh: ENC[AES256_GCM,data:0OYhpKyzJtvdT/Rf9Unu7pIy2G/S8CeHemwsOfS6efwMjpAJ7UP9f5Sh0a3H9Eu9tQOZIqMk2B3DElVhr3y5q3MQ5I9qy1Tn9R5WQ07s+iyRucDQApLpZ60/uRRFgIXsCTVSP080PLNJwsQfGjjq+CrrQpONjR9+qMkZU1uN4uecvuZ2vLh7KQidHMOblZpfBohE9+CcL9kFvg3NC29fqCPi16F20nrpBNWqoyZeCoTTmTUI/DxKacmQeH+5wmsyQnw6wyN6KcZTys7zwHiUw6X3j+eQkfaTO0VAPtkX3czFlmX+j9Q5S1HNQH3y2lyRj7aQVFl3IdHbxP6ys0zI5ktsln54Jdt8BIPPDHB3iTLVn6hPyY7pw3LuMNfKyE9dgqz1xPTPeDKwUXqt3V/tCx5vzmV0MWdKGEMdMQRWQX3PHb1zQ+Dv6cN+8KzmRVevf9IgyTb7zuk2JvkT03reoRRB3ZKd5qx4bFX7FwWY6u0nVWQP2GHW/ey9tSvbvU1X2R1zQaicL2WEewQJ0kYYEQ==,iv:+u4xSn97ncZ1YKxMki6vTQIw+YZrPrOxnIGqhESyhwE=,tag:n4SkFLBNmtV5XKz2uqvDLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscE13M29TRzErb2dPYTlz
            MUtzMTYvMG11K3p1WFFyNDVkaVkvL2lJRkdrCmlXUFJJL2ZOdGpFaEh3ajc4dG5q
            UTd0VlNFcWJsMmNKL2FLWEQ2VWJ1QVUKLS0tIFlEZ3ZGeFNqSkNFSFdhNHdpeUF5
            ZEFwNWRZMzBjNXJhK25Ra3hwRW50cGsKvQOcQcKXPWPtSCozerlrJ/RSfkORjtsH
            /GLYiG6tReRvXSXsH9B6F7RDKgke+j6xAb0u8Px2OaK0BYKXVGqMNQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s3upav4x8re3wzwvuykmjakk52d8xukw7c9jxa80z8zj0lyxgyysenzhen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0K0g0a2ZPd1d4WWdQK1NS
            UGNZaC9wTnVwbUlJL2FQN25rbFFhMysrTDJVCjZRL2x4b2xtTk9icUduaWhxTHhn
            djB0c3pYa29aazhpMzlzSk0wZG16VFkKLS0tIG84aGF4dkd0em1DWnBzaEJQWGJV
            TEFFeTlPR2xMVzRzUE9hN3NiT1NxV2cKnDyaiceFPZdl36xtflKnrj09zQC3mGMm
            GyHmQpMR06jhxifByshSv/HjpSP1CIqDJu/TQ83K/gVNDv8Y7sZcEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-13T18:38:06Z"
    mac: ENC[AES256_GCM,data:mZX6CiO0LUgZzHv+Aw3d0YbEc5oT2x0XLQWYZRXak09v1K2Dq2vJPZAqaQOuVg0SW30qPKJEjbWorMAuSMIrQL7/p3eIHMbBa1jxPVwL0qUcH4OSpMlEQlrWVqm2e8iMDsV1XYh/Hedv6aTcfv8UA5E0aaRC/Wgdx3eGkkoedno=,iv:/RvI5uYiAfllCDknS6ragJI57c4ymgDRi2Fi8Rfao7I=,tag:pgXFrNN5AoNIoPe36ZnyYg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
