wakapi: ENC[AES256_GCM,data:2CwnBLXSkM+XRICx5kQ0PW4MCrQElikV7yN79ZI7eszbA+kaQ2zPWxAwnFtpfIxG/OAMREDDXrBKMXfij9dIlIjm6sS6Z3h1Ij2DQuT2gxKLJPkzWlv1hn9CqjEm3VqzeDCkWQiVFoWWAFI5d33zR9/wTmy+fVS+bHbigjkpvzgcpjShN80bYRTwayHuvHaWy88ifDVXf+c2,iv:1NIaQqyXK+RA5330+aSQVP/99NQv+lzyCMteejH00H8=,tag:WbPbxmLbq5xYPo3WBNSwYw==,type:str]
swdemo: ENC[AES256_GCM,data:llrGLajCslDsKxbchw3ghZB79TR1sQwZywdFuJJQsXi5AlydDuhXXc0xrdQQsXP5nlCRejGEptQC9Y0UPWybqgx7TutPqjxS1h1wyzXdL6oZUusqBbPzar19WPuYi4aUEzu6318aEKMc8SJFJKxgt4wNTYv4Zipk5Gt4wVP0aEwHsDwvc8I750AsT/p8NONMApdJ2PSnrwJRTRinqKY=,iv:lKROEumx5pesdU5jAkXh6Wkbs1p+LyZzHljpUmTaKBI=,tag:QZlNXTUMZ5skoFPyEpfzjw==,type:str]
grafanaCloud: ENC[AES256_GCM,data:E28fu/aEL04tEPGAmsLYGdMTQjS1GMW1MyH094HoHyDvPObmKCh4Co1ZtZ03wPRHYzrCutjXH8xqE5L0MK3GPimosx9+bepz4cGyC5Ha1mGib/cYISApGiwfRZ8HDkVzotS1ar8xGKpNLqg28UdzCn453BEUEhctt23nen70ngCpNRTiDpLvt8FK+aRgfgOl3IB7pdE/,iv:kzi0icQwlE6Uz/ZKYJ2zo006xEKRnh5rLDRHbiAwnOs=,tag:S9LO0xPLF6jjJ8SDMapukA==,type:str]
traefik: ENC[AES256_GCM,data:iZIV2LdQm5uOO4ISgwY/VDaA6QUt7T+IZ4TV8v+iWlvgCESy/8xZP8on7i8MZhZOFcTekYuFzl7OaA==,iv:72Ai8D+ATXdbyBMH9J6CAUQoj7B1KKtgdg3mQqih6vk=,tag:DN7ElYVRIRWWn0umqIWfvw==,type:str]
sops:
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnY3RuekZPU3JLVFNNVUFD
            bWNIUmk4cU5Nd1NiU01oMFc5dWJyTVhFdWpJCkJGTGF2Wlhidjh2UnhjWDZuSjFq
            ZVpNQUxyb0tUYytWcmQwWTdLWDZudDgKLS0tIHN5Z2NtaDNVYU80bjFvREN6WDdq
            TTUyazdNdXR3SHZZcG9xSFhqRWpxUEkKmxVrK8Rkt1BB0eoDa/toQ2UfnwzQ8/V/
            b/RVH0BVcvU78m9yHvbaUoPAErPiM/uidVGoi+1OZPkvntCZNhpkiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dks5yn7u9guqk9g8gs7panm6xkr72h9g9v8lnustwg4fsm583msnjma6x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVzJvUnVOV0xtRU00bjdu
            UkdsaUlsZEQzMjFUeHBTMkZpUFZac2RLNmpFCmthMkZwOWdqSGNOTGxsSy9PcFU1
            UlYrY000bkNxc2NoV25mc2pjTHNEZncKLS0tIHV3cVEvbGlHcE1YK1FHUWJKUFRz
            Sm5qR08wdmFxWC9sc0pucE9DWWNnN1kKwthSn2BX12zZyGeCdSepX4zIs8NG/W2X
            +CLmMuFyZvBAGbGWHDJZpZOgZfv62k4b2AQU/DMY9XJOpqk5RJKo/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wq3nu4vt2l5m5sfar678px45495h6zkdp27gt95fpxpx5777098qp5t0h3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSDJ3ZFBJQWQyaUxuWmty
            aFpxYkd4LzRadUduL0h4bEF2KzFkWW45ZVVNCnNSbVIrT2dTNi9HSVhhTTVCU2t6
            ZFF3bnRkVUFTTTB4TUk5V2JGTVJSZXMKLS0tIGR4U2ZZNWpMNFpEV2tqK0xDbjc2
            NVVtSDh1eklmQ2pKK0xYR2d1aDlDajgK6ZLkyrl/1YQjplKuvHiOrE+aXVAxYzwr
            YUNB2ncJym9XNry9O1lxSImsNe0pRP4muaZxsa1MdW6uFTm6kB+NJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-16T21:26:42Z"
    mac: ENC[AES256_GCM,data:3XbPHmQAtS49C6Gr2KDAO4C0yrdak7b3ocCdCdzZ3jTEw4CoStxMqbnw3wAOcrY8eZlOyUm1hFk8SLmH4bvSpPmTHRWP+vGT60E80J6ltLa5lE8iHmdVI23F19kUVqSa6Lxe+OHCMHx5cMbdYc7yGPNO3KfuTsrVWMudJ9LYmSk=,iv:s8o9A3czG6LXN/kZAoAk8fuiEyXZIiMeRgB/2idO+3g=,tag:41gnBszoKFzOJUNt5oAwvg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
