wakapi: ENC[AES256_GCM,data:NNu6Iuf8l3uf6fi2mO6cwyR0ZgyUL5KqPUOW1FSPo1/Cx2dlX/3Qz04KVarBOStSyeGBBWNpD+CNDxLoLvP47DWnIXL73iuvz3lLKUkmYSfgxCYgWUsn/jufIHS8c3O9O2rbugx6WFHCudiFG4bObm2yuukhteGZvSfrSqMlV+UGuSA6irdHevff72QwZMyEpEQ1X7piYrDq,iv:2j101eDQr3XBA7IPhkP8BHWB1bpfqnfQTrtGV8ZSe3I=,tag:rY01AOU8IAFr4ho8lzUSfQ==,type:str]
swdemo: ENC[AES256_GCM,data:gMeyuZ34qS+E1Rid2C/6Qcit/4dYgZYvdCDoEVDDhxo6gXHX1Dlw7G9i+zIm2cEXSOrdjkMLlVxeaE+V3LTouGXtXc2eR/JPTLrTlS5uFeCdcSvdht5Ffxo8guNkkPuR9AmKgI1ooFmHKIQbQIW5eXKBtsgH7km7qL5WY4IezcsY+HpU19yFZfzu7cVNL1hy0FmpYDGjpYfz9ONSbOs=,iv:qavFzQ2g0I69VAgktwRxHWv4IbE3aUpYxikE/mPQdko=,tag:ADsE9O2mzImZatA89SpOoA==,type:str]
grafanaAlloy: ENC[AES256_GCM,data:b3yToHCf0fJp2pjGFdjRyd+CgclI3pgECau5Wk4oS80ZV3OJuWkTvpppmz0r76JznZjLxJcKpNmqWpMtYqB0z7oLr9j52Ph82yJoBb4wUBHeSKXRT2zePAz2c3PtRz2bhSsUlyZeBrEZFOJmW9rtzx4bCVthUxrqNt2pKiiAWioZD1EUS1DYmlOtjThMFB5DLi2/kOgAZnPO7zEQ6JYyeH2jnC9s,iv:hTBqoduMCT/r3nA4SuhU+5wBKZwy477XjkxMJUMUR4I=,tag:vzn2R/fB9D6GbMruynVtfg==,type:str]
traefik: ENC[AES256_GCM,data:PHbs+QXbXqqJjeMRQRODovInG/kjR7pUsibhnPqpkko50azZBe6Z0kduBHOAZtDpHT3h6759m37jGA==,iv:JQrUHtiigCwcsqkyMR0YMUT9RrjGjY7RvE0MT/XNIYA=,tag:phWlu+HJsubOl6zlg1sulg==,type:str]
sops:
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSGNQU0pIa29oVk1kTFNw
            TnpEK01HbzJzTisrY3BuTk4rY2lVTTh2T1MwCnVJTHZmN0xMZy8zQ281aWZqVkN1
            d0RMNEN4QWFXaFBUa1VYN0R5TTdGTTgKLS0tIHo2UkJrTEU3VDQ0cE9BaG5XbURO
            ZGNXc2g4MVlEWHAzSHBWN0w2eW1nS1UK9fG0PVr1xUEAfAiB5ROkRqI9kMjsylOM
            qIn2Z5bYHVj8llslBCtm93Ml+0om11MV2fGx1TJqYDCihKlkPuWGfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dks5yn7u9guqk9g8gs7panm6xkr72h9g9v8lnustwg4fsm583msnjma6x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTC83aFMrcU5XVE1TZFdu
            a2l6TXh1dnlsaHduVXZpQko4WmozTndiU2djCnJyTmFscmZWTFlRYWFiUW5mRnRK
            Ky9YWGpxUlU2L3FlZmhiL0lHUjhEa1UKLS0tIHNtcm84NmQybDBHSzRPWTFjMUhB
            SnFoZ2g5c1pQOXF6YjRnNk1aUUhncE0KzbJB41ob+MTiGX093AvzPKScfmmsBAwb
            pIWxoRxR/H0Zc94lLxXS5BoDzMx2gfXMGRq7EnD28GH6v1/pMWVODg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wq3nu4vt2l5m5sfar678px45495h6zkdp27gt95fpxpx5777098qp5t0h3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSDQ1ZU5mV0hRaUxRMFVD
            TzlDTUlqVThxT0pBeEtCU2krVEt6K1R4U2lZCnpqZmVxQ1Zkcld5S2JNMUh0N2Vl
            dFhqVVEwTUlud0dubmFQL21LZkV4TjQKLS0tIFUyYUFMWFlXaGJZK2YvV1NyVjQx
            eXBwcGlRSm1FdXRMWElsdkEwM1llWDQKZz0hRrHtlDxNcHdRtmWwS15iRcH3FxFY
            dMEeP+UlEvJnlYGKkr7fd8MWqzUJRab71uL1ynREIwt43lNxlpQJgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-16T14:31:47Z"
    mac: ENC[AES256_GCM,data:1nt4j4E0///3MfmK+8J+AikV/tYOmQaNazTanDW1wfmZ0IEheKoQqSPG7lGJXlZMMe1DpzRtzu/qSzfYgQuGqu6TJe1uRfRQICqJHnrbTtMU/xygs/mLlPGocLVgQUHd0t4lJDx3ra+8G+Z3rINNZMuERku+JWKT8ntDOkPDSwY=,iv:mk2pQQmpAw3hvRBVHgdV5l79+tIXD8DLAyyQKFd6D0U=,tag:xysIy51EAfrI5B7yQGQy8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
