wakapi: ENC[AES256_GCM,data:TtmpvbYnxwvBH0r/+3JcffRVUHWpDK7xnwPTuv04B1gGEI+AVu+5yyKA64cdfD0Rh0IKwPJ3NWgIDsAZHxY9RcA26CaZ+qNMMNeAzg967AznaVSCKJQx+dEc+wYH0NtdIu8Tk9LoMILN5rvV31nVveSCFWii6KBJtBDX3DS8sMbAWzhtx7fANYne80Ch54ez9EWF+O0nemt+,iv:W93rb+sEJAKmJDyqA+lcJ/CZN110OWT15Em0gcJ3geU=,tag:/60CD4nko9ACvIsprJroTw==,type:str]
swdemo: ENC[AES256_GCM,data:PkSPLMelPT/HIJjsmNzl7FW2hZqqci9DjDl14aaEk/yIfm98NZdk/UVojmWElOrFLyVvlGjtd+ukHr90qnsATTZxSk9glfTJBHhbH7eAR8qfTZqFRSH1D1TCRvrVTSpLXupWKhhHeKg//zfjWDrr71nFlj1/iUOtodGr9uDL0JG3WVkyQDfeU1G4VwtlRnhxRkw6yie5rVLFLnm0Kzk=,iv:7S+5xgvfSqvBt3RBnQJNH0dpFu7FmCErKk5zhUAZoyk=,tag:M4roKh1JKwm2yVW+PIWGLA==,type:str]
grafanaCloud: ENC[AES256_GCM,data:kSCUunc6y1Z41PwH2Dr45Gc7ZPu3meF8XFGK25dSDZ3HfR2opBebcMDGJsvp7MKnZShGBNCabjtE4lnFFIevVQCvcDbt/1RMhc11e8Qmwl0DOWyIcpziuE0aICyIlPAIVADqR1CoWmXFSPXYaIeOQIpRSwAEkn9+JyVmHAkjccOjdVEP3DL1tVR9M8kzPNXMcV9QjLbR,iv:OPeBuZuf/f0pMGqDgN/VuGiXApj0Y9zci2w2gdmKPWs=,tag:NvmWseQXpJlNN9m+SSIIKA==,type:str]
traefik: ENC[AES256_GCM,data:ZBUTSPYNYGBxa2rB1Mmcle+eiY/Re+k53K3YxV7hhkJY5vhFgpytMnnWxYhq+Uoy+pnuN5qZiqjI7A==,iv:zHYhYPhAYM7dtViLFqIQxa8NEjhJ5DsvkiOyDDoQ11w=,tag:Y5mCqS/7ALH665Udl8q+UA==,type:str]
sops:
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZVlJTXk3cVhwdEJ3TWR2
            YlpIUUdDNVA0VUdvZVFXL2ppTTdNQ3hDc21VCk0zcyt1NTc2TG5LZEJ0eEJZTXpT
            a0FEVDdQMVhxdURaK1VieDNRZDNoaVkKLS0tIGdocXNpWUlWeVdzTlZOaWxOcmV0
            bTI0ZlN5NGR0OWw0bmpUR2JIVG1QaEEK3deKRwqDRoERu82xn2zqUFrk56eklhzf
            FmGyY1vjzERQJUG4IHWfpF8SFcMJe3CFTg/7upuNjJVIYZdlr4rKKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dks5yn7u9guqk9g8gs7panm6xkr72h9g9v8lnustwg4fsm583msnjma6x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNW1SZHA5WkNHK3k1cWtJ
            dlUxdk9FaDc5dzh2dFRITUFaT2ZaQ0JWT1ZjCnRiWVdaV1pRT0ROTEZOcmEzd2lm
            SjVkK1FicWtzTXVRMjM2dThocnFqVWMKLS0tIGYzLzNmNElqcGdQcHN2NU02djA3
            bFhOYldmbjhqL1RsaU9zU3QwQW5NUnMKf239yz6X4cnEBgXp26WtVSu78kUtJRJW
            b6j7JNMo30IRRw33SGGvJY9njMVTpA57Vz+GXAv8k5Qmg+oGx9JYSA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wq3nu4vt2l5m5sfar678px45495h6zkdp27gt95fpxpx5777098qp5t0h3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTFptQ2xDdENiTFFLRGpM
            RjZvNGNHNzV2WVZUOXBKN0tWTnNhZWRzb0dzCjk2TG5Ba2JXWXhGTDhtRktMOTVP
            N1N1Mm5laFcrcTJ1R2JWQ0NROHVDalEKLS0tIGtDWUJRVWVvclNVbDBEQ3BDNW9M
            TTB2OTVSZ1J6RXgxeWYxKzVhcWhnMmcKMXmNPGH1YjKqxcMU8loH6KfYgZi3Gdi5
            UZw/iTccz94O3sGqvnEFvC+qZTxaAGZZUBeleJAoa+HMYCcOwmAVzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-01T22:05:22Z"
    mac: ENC[AES256_GCM,data:W8CN2j8bfJ89KZMFfU5Di0QV+cCM1i83ZCn4ORQDwoREC1WdNUJFEVmarXF0tMFsBVoasVPZdX1Q4Z6BCbbhW9AqV6J02PYTNwwHdbMEjs1VOQsbxXXGAMX60fmd82kgYnweYtncOtChyJ10pbkRyiwNyXLG1T31CNx831Hgliw=,iv:0Phcan978U04mXg88p05Fcm9WXFUrODnX+1znB/ZS9E=,tag:LCjC4B93YUaPV5dB/gJ9Tg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
