wakapi: ENC[AES256_GCM,data:Dr/G6IhUZzBoyz6i6bJqfjJSFhB721HPr2X2OEE65MXLRA==,iv:zE79wTUQ0nEDA1cMwpv6nBOoPk1c8JY15F0nFTp0V+s=,tag:QpI0FikRD2Pl2ox32t59Gw==,type:str]
rclone_config: ENC[AES256_GCM,data:BXP1I0JYgsswjTaIYN5KhjbjBLs6tGibgDRKM0hhQQxsiWtIrFXaFy3pMdbeAiRqeEJvCY2tS/Mmb8t1OkzWRnCzkU0BbidA5sXmYcnYadP2YmHPPiLrYHMpmxrL8FkntURc6YFvD2ACBeYsJJ+NlY0sJyMEp40qy78Pi5S5Cyzq8sUuIVsjLbZJ66yt4NrC47gpVg==,iv:28LgLl50WRZwNW69dGA29pszeXC30eyj0J4aE+C8Ato=,tag:tOFxg0JmzPErEr5jp9hkKA==,type:str]
restic_secret: ENC[AES256_GCM,data:/UmfUB2eJSp2Zdz3FPOoxaCjq3CFHf3topU3ZU3icJo=,iv:ZpC6t0L1zma+YEZOMtxJtXY7OPCfGHwaxsZ3OrSZSjU=,tag:1y1gK2nKWMUC15RGShA8vQ==,type:str]
coturn_secret: ENC[AES256_GCM,data:GsZ0Jarz0Upa5fCvKF256u7oMycW2FzBcNFHfL5zY8s=,iv:36TMmELBwya5b5XYNkX4TRTYuP/CCfblkOPA5Dr1Itw=,tag:71kgLe6DpHaw3KUyGDslvg==,type:str]
screego_env: ENC[AES256_GCM,data:spHWdB/1gxXZdBd4dwztfom1Wiy2xLffmM/b8QtoEHVF2WmJ2Uw8EmyrEQGqT8lb3bYMwK8fv0tr+krPGw==,iv:Sc7HuXXN07wbJrz7waOk9EH3MP3Hja0Gagd/dj1J/3w=,tag:WrUv/WuIpCzuFBPwXtx+kQ==,type:str]
yuzu_room: ENC[AES256_GCM,data:htno1TCd9DAduwn5BVJ0Tk3ySYj6/Za8bD5CEHTkZoQQ1mDmQ93fkqrXOoQAl2I8DMZGo6sDHRMrUk+CB+SMkLcUG89/MpXX0w==,iv:iYVgaUsAszBN2NJk3Gaiy0/v+vos6qKtxeOPtunk8c8=,tag:1nuhrFeNNaUkfGFuClVHqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZ3BGMFMzcVEyTHFkaFdY
            VWNBam9Wa0t2VzIwWUFMYnlEUHM5eW1ROG5vCklYb0hvUXRncHdZaVl3Rnc0ejE5
            eklHTmFkYnVsRzNrY2pqYVVrL2w3cmMKLS0tIFRrWTE3V3JMdW9YcTBka04wYXRZ
            SFY5SENKbEQ2U1JHQzEvNk9ubFV2Y2cK3CcA6vOT/8WBJWMja78FPT5bnNunTFWL
            6ruNS22kzHUUjf0hWy2zcZUVck8Li+3UeYKm8YPiM4QQoevgfdYG8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s3upav4x8re3wzwvuykmjakk52d8xukw7c9jxa80z8zj0lyxgyysenzhen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMXNubmR6SkpsZVhDTThk
            b29GYzArcVUxdVBQY3pFUkc2ZWt4eis0aTFFCnlQOE1BODRTRWprWVVjUXRtZVNi
            eFFoYU1Vd0htZmo0QkFVb1JsUHlHZXMKLS0tIGRuWEVBUm0zb3owRkl1UDBEWDNS
            N293bzJjN3B0bFg1OGM1cWxrdUVTb1EK/uMuxPEhUVZg1fJGvZDsR3SEZLdcqrUH
            Xx0SihcBsw40D7r5B7uD20i07fqh4w4MO+mpXB2HMfXbiDjceHqAtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-18T11:38:22Z"
    mac: ENC[AES256_GCM,data:Jylu+YbulJqTrEXpfB1dcKsMPTJ3JfdXYPDhGmdA/Hro5oqMgjYGXG8JEyBdvZDxhfjllkk3FPqcrlnWiz2r1+aFARehAaVz9SIPbOFy770jI7QfuVBFkgVI95rUGhOu2wbRG9nqemYZOkH9mPqXMuwPbHstwJE9KgXGbOWP8d8=,iv:8vzgPiHreVtbBMil4K6x+s10IKiMZ3U1cERSC8J6Rvg=,tag:dxjvp7taKrF1/AKQl1qeoA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
