wakapi: ENC[AES256_GCM,data:AJOmmqaM4QrCyPmwgAtsORoUwsDdldupzhPnY5NIuyo3rGsncO6rJV/sxMuB0fUeL1G0F1NygJVJT3GooK+f/LpG2274HNyE2imGePBJJEeetY5C6vecmQwxUYstKJXPWN+sgdhWGN1a8vrKaE9HHd5nSAOyofEcUCe017pyBYPsPDfBlTAEyfN4r6Cnkj6g8uU0egAV2MEV,iv:XYXyNeyu9q75CLtkV6M08heLMwZ+yHPoHHuIVwP8xDU=,tag:7MVrtCB/WpKB7dYpd0NeYA==,type:str]
swdemo: ENC[AES256_GCM,data:KjFMFi05q22qqn3uivdEZlnEkuuBWzxb9xVaAA/nl85O60NxFJS517t4bZHu2I5yK5JULkeS5TWS6Qeuoc7BsdXJFF9cMdJFioLRJgAAn6urKYDUo0M0sjF/ByDxjyM7IOEL/ZNU+l73iaDlPwQ5pgoEJk6jOQymxY/XHGr0umbIwOgkiSLTJw9WJKNq9jCSX31uKEkDMcHo6SI38BQ=,iv:+mgQy7ejgy/NDXz/gwNqHhAmmbj3QMfJksi6UCmnAsI=,tag:1JKzgYn1zzagKoK4PB08Yw==,type:str]
grafanaCloud: ENC[AES256_GCM,data:3KS3rxSHDi4WLMoouubE5ip7wpv+66ObTR9d34cx0YcE6ifbH6AOCVhe+Zov+h20fS5BbAtF5N0BZCcwpWufbmRL3pSwSF823sIhtWj2lrYtTFEMy/ri3RLWHfY76IYi8RSJRU54kNunLj5VeB4prEw9RV8bwf4OhUAljOPkSez7emn5P09Rg10o5m87lfkrs7k1P6AL,iv:PXChpkgU0QNnJ/4gT5wxXbajVV+uqEbsOyRHD720GYQ=,tag:0WhpWmt0kT/Ku2pGKTarHg==,type:str]
traefik: ENC[AES256_GCM,data:n/hJLwRYZNu9py3wgL6uwYJnVIzATmKIU6m4+FlVS/re4cmF0K1oyjicL7Y82MAZjNo+lmTvSTUVxg==,iv:eVwlRL/yC7y2zxSze12FOOvqLwrgUGXjAmMl7Oi59Zs=,tag:SAjgLx1i+1PCUW4Hwmhx0g==,type:str]
wireguardServerKey: ENC[AES256_GCM,data:3qMWV3ig+siORoEPkh5uW9xvvFxWhXBb1lg11OVlGP7nTyYU9APcpq6FaqU=,iv:h29/ls3N5uWZtVjCRFAo53hJ2SIhnm4yKD2rVUi3f7o=,tag:nmxRALwPo8rZD/M/+na0Fg==,type:str]
sops:
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbkRtSnZrMU5wOFMvMXU4
            djlDVm5VcDJTRG9YcUtVUVBBSG5sOFAwVmdJCndLQVBjMUt1UGNmVkxtVEtkamli
            c2NuQ29mRTdpVDNTWTlud2o1ZUlLL1kKLS0tIFh4eCtvMHYveVhOTHhBVGYwalN1
            MzRzT09aQ2JHckJ0ZW1Rb1RUTlNKTkEK8m0rkTTQ0+20reGl7G6K7FJcRFkgDuHk
            yKulcHp17O5i65JRayIJJ+tfOOyrxbfM0jHY2F8kEAzHhe33ObFz5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dks5yn7u9guqk9g8gs7panm6xkr72h9g9v8lnustwg4fsm583msnjma6x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZHBZaW9ZaDRzdjZGaGVw
            NFhQWjNGT3dtOHA3RjlVQ05UOE50ZHRCQlVJClZqZ3JEeVA4c3A3V2Fqdlc5Q2pP
            Z3BiSmNkc2RUdHJFWUZ0c0JaSHlpdXcKLS0tIE5IOGNzRllEMUFVd3p5aHJGOWh5
            bE5tQlBLeUxqdVp6eDVMOWo0UDV5d00KcPWpoR7F36b1ROXHxAbuu9rwDeoptWNs
            4dL/eKqmpE+rIJr29+Uwf1i+zHTSMqDmK8ePIxDIiLUYdVpYthKd2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wq3nu4vt2l5m5sfar678px45495h6zkdp27gt95fpxpx5777098qp5t0h3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYmQ1TmRMSVFXZUdCUlpU
            dnVSYXhsTUUraUhRWllodnNocnJLV0M2aFFjClVnSm9SdmlJdVA0VHM3eEJmZitY
            ZkZyc0paZnQrcWhPdTd2UU14SjNLR00KLS0tIHArMnhIUGNvSmlFVnQwSklsN241
            NFZCNnVUTjBmVjBsREJ1WlQ2b3ZGZDgK6Al37/QCXWTM2ukrHg61KG99HjcvaPMU
            m0oIrTv2YaXu6dQiBH8vnHPobaJThnZTBJDBqYvVPluoedfQraBhhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-14T09:08:37Z"
    mac: ENC[AES256_GCM,data:xCExrcaSnMvHrYGpVQTegWV2DF35G7olTwi8kr9Dp9Ab058D+0oZm1swzpAsmeRKsGrhxSh6Jt+3pu9D3ot9zNjSAZ/rncAaw3pj/u8e5NfB9cSMM8FCeIMMVs0CliIIyQnqV9HHht4yxD8mLWTnkpA8klP0W1dvilUuirkpE+w=,iv:pN/inFuDxsikBGKjeFdGExpXpOtov3mP7W3esM84hKo=,tag:N/ZfZUkqndJt1B+etzDEWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
