name: Shea
on:
  push:
    branches:
      - main
    paths:
      - 'systems/shea/**.nix'
  workflow_dispatch:

jobs:
  shea:
    runs-on: ubuntu-latest
    concurrency: shea
    steps:
      - uses: actions/checkout@v3
      
      - name: Tailscale
        uses: tailscale/github-action@main
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Build config
        run: |
          nix develop -c colmena apply --on @shea
